### ISSUE TITLE
edgeR imports fail in Quarto documents

### ISSUE THREAD

**Issue by ethanbustad** [FredHutch/seatrac-hackday-2024#1]
Running the `granuloma_tcell_dge.qmd` and `iv_bcg_dge.qmd` notebooks on the provided hack day R server using the `extra_user0` user yields an import error for `edgeR`. (I assume it will fail also for other users logging in for the first time, since going ahead and installing the package put it into `/home/extra_user0/...`.)

Adding an R code block to install the package (the following) did fix the issue and allow completion of the notebooks:

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("edgeR")
```

**Comment by agartland** [comment]
thanks, i've added edgeR to the Dockerfile. this should mean it is not needed in the scripts themselves for hackday. can you check and see if there are any other packages you like that are not currently installed?

**Comment by ethanbustad** [comment]
Looks like `janitor` isn't installed. All the other useful packages I could think of imported just fine.
